title: <h1 id="demo" style="text-align:Left; color:white;">Kolas</h1>
description: The Temperory Page
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
github:
  is_project_page: false
